/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminNewPostRouteImport } from './routes/admin.new-post'
import { Route as AppsVaultRouteImport } from './routes/apps.vault'
import { Route as ChangelogIndexRouteImport } from './routes/changelog.index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog_.$slug'
import { Route as KbIndexRouteImport } from './routes/kb.index'
import { Route as KbSplatRouteImport } from './routes/kb_.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewPostRoute = AdminNewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => AdminRoute,
} as any)
const AppsVaultRoute = AppsVaultRouteImport.update({
  id: '/apps/vault',
  path: '/apps/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog_/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const KbSplatRoute = KbSplatRouteImport.update({
  id: '/kb_/$',
  path: '/kb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/new-post': typeof AdminNewPostRoute
  '/apps/vault': typeof AppsVaultRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/kb/$': typeof KbSplatRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/kb/': typeof KbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/new-post': typeof AdminNewPostRoute
  '/apps/vault': typeof AppsVaultRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/kb/$': typeof KbSplatRoute
  '/changelog': typeof ChangelogIndexRoute
  '/kb': typeof KbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/vault': typeof VaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/new-post': typeof AdminNewPostRoute
  '/apps/vault': typeof AppsVaultRoute
  '/changelog_/$slug': typeof ChangelogSlugRoute
  '/kb_/$': typeof KbSplatRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/kb/': typeof KbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/vault'
    | '/verify-email'
    | '/admin/new-post'
    | '/apps/vault'
    | '/changelog/$slug'
    | '/kb/$'
    | '/changelog/'
    | '/kb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/vault'
    | '/verify-email'
    | '/admin/new-post'
    | '/apps/vault'
    | '/changelog/$slug'
    | '/kb/$'
    | '/changelog'
    | '/kb'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/vault'
    | '/verify-email'
    | '/admin/new-post'
    | '/apps/vault'
    | '/changelog_/$slug'
    | '/kb_/$'
    | '/changelog/'
    | '/kb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  VaultRoute: typeof VaultRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AppsVaultRoute: typeof AppsVaultRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  KbSplatRoute: typeof KbSplatRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  KbIndexRoute: typeof KbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-post': {
      id: '/admin/new-post'
      path: '/new-post'
      fullPath: '/admin/new-post'
      preLoaderRoute: typeof AdminNewPostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apps/vault': {
      id: '/apps/vault'
      path: '/apps/vault'
      fullPath: '/apps/vault'
      preLoaderRoute: typeof AppsVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog_/$slug': {
      id: '/changelog_/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/': {
      id: '/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb_/$': {
      id: '/kb_/$'
      path: '/kb/$'
      fullPath: '/kb/$'
      preLoaderRoute: typeof KbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminNewPostRoute: typeof AdminNewPostRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewPostRoute: AdminNewPostRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  VaultRoute: VaultRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AppsVaultRoute: AppsVaultRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  KbSplatRoute: KbSplatRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  KbIndexRoute: KbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
